# Generated by Django 5.0.1 on 2024-01-18 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('letra', models.CharField(max_length=3000)),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='musicas',
        ),
        migrations.AddField(
            model_name='album',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artistas.artista'),
        ),
        migrations.AddField(
            model_name='album',
            name='musica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artistas.musica'),
        ),
    ]
