# Generated by Django 5.0.1 on 2024-01-18 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0005_remove_album_musica_musica_do_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='do_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistas.album'),
        ),
    ]
