# Generated by Django 5.0.1 on 2024-01-18 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0006_alter_musica_do_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='do_album',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='artistas.album'),
        ),
    ]
